# Generated by Django 3.2.5 on 2023-04-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_result_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='AWS_ACCESS_KEY_ID',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='policy',
            name='AWS_SECRET_ACCESS_KEY',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='policy',
            name='profile_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
