# Generated by Django 3.2.5 on 2023-04-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20230408_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='AWS_SECRET_ACCESS_KEY',
        ),
    ]
