# Generated by Django 3.2.5 on 2023-04-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_policy_aws_secret_access_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='case_id',
            field=models.IntegerField(default=75923317, unique=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
